kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "master-pipeline"
spec:
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node {
          // define commands
          def gitUrl = 'https://github.com/jacobborella/ocp-builder.git'

          stage 'Get all projects from git'
          git url: gitUrl
  
          stage 'Identify new/updated projects'
        } 
