kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "demo-pipeline"
spec:
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node {
          sh 'oc new-project demo'
          sh 'oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git'
        }
